--------------------------------------------------------
--  File created - Thursday-July-22-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CORE_COLABORADORES
--------------------------------------------------------

  CREATE TABLE "C##REGISTRO"."CORE_COLABORADORES" 
   (	"IDCOLABORADORES" NVARCHAR2(10), 
	"NOMCOLABORADORES" NVARCHAR2(30), 
	"TELEFONO" NVARCHAR2(10), 
	"DIRECCION" NVARCHAR2(30), 
	"EMAIL" NVARCHAR2(30), 
	"PAIS" NVARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010262
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##REGISTRO"."SYS_C0010262" ON "C##REGISTRO"."CORE_COLABORADORES" ("IDCOLABORADORES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CORE_COLABORADORES
--------------------------------------------------------

  ALTER TABLE "C##REGISTRO"."CORE_COLABORADORES" ADD PRIMARY KEY ("IDCOLABORADORES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##REGISTRO"."CORE_COLABORADORES" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "C##REGISTRO"."CORE_COLABORADORES" MODIFY ("IDCOLABORADORES" NOT NULL ENABLE);
